---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: ''
  label: Home page
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*"
upload_dir: Vagabondians
public_path: https://res.cloudinary.com/donblanco/image/upload/v1587408001/Vagabondians
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
